wandb_version: 1

algorithm:
  desc: null
  value: DSQN
learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: SNN
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712152808.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.9.18
      5: 0.16.5
      8:
      - 4
      - 5
      13: darwin-arm64
